# Generated by Django 5.2.9 on 2026-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateField(verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateField(verbose_name='Дата початку'),
        ),
    ]
