# Generated by Django 5.2.9 on 2026-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='Опису не додано', max_length=480, verbose_name='Опис'),
        ),
    ]
